name: ci-build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Cook, Stage & Package UE Project (Client)
        uses: OrchidIsle/UE5-Build-Project@latest
        with:
          RUNUAT_PATH: "D:\\source\\UnrealEngine\\Engine\\Build\\BatchFiles\\RunUAT.bat"
          UPROJECT_PATH: "${{ github.workspace }}\\StereoMixPrototype\\StereoMixPrototype.uproject"
          BUILD_CONFIG: Development
          PLATFORM: Win64
          COOK: true
          STAGE: false
          PACKAGE: true
          PAK: false
          SERVER: false
          ARCHIVE: true
          ARCHIVE_PATH: "D:/archive/StereoMixPrototype"
          EDITOR: false
          ENCRYPT_INI: false
          # RELEASE: "0.1.0"
          # PATCH: '0.9.0'
          # MAPS: "L_Main"

      - name: Cook, Stage & Package UE Project (Server)
        uses: OrchidIsle/UE5-Build-Project@latest
        with:
          RUNUAT_PATH: "D:\\source\\UnrealEngine\\Engine\\Build\\BatchFiles\\RunUAT.bat"
          UPROJECT_PATH: "${{ github.workspace }}\\StereoMixPrototype\\StereoMixPrototype.uproject"
          BUILD_CONFIG: Development
          PLATFORM: Win64
          COOK: true
          STAGE: false
          PACKAGE: true
          PAK: false
          SERVER: true
          ARCHIVE: true
          ARCHIVE_PATH: "D:/archive/StereoMixPrototype"
          EDITOR: false
          ENCRYPT_INI: false
          # RELEASE: "0.1.0"
          # PATCH: '0.9.0'
          # MAPS: "L_Main"

      - name: Upload to gdrive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: archive.zip
          name: documentation.zip
          folderId: ${{ secrets.folderId }}
          credentials: ${{ secrets.credentials }}
          encoded: false
