name: ci-build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Cook, Stage & Package UE Project
        uses: OrchidIsle/UE5-Build-Project@latest
        with:
          RUNUAT_PATH: 'D:/source/UnrealEngine/Engine/Build/BatchFiles/RunUAT.bat'
          UPROJECT_PATH: ${{ github.workspace }}/StereoMixPrototype/StereoMixPrototype.uproject
          BUILD_CONFIG: Development
          PLATFORM: Win64
          COOK: true
          STAGE: true
          PACKAGE: false
          PAK: false
          SERVER: true
          ARCHIVE: true
          ARCHIVE_PATH: 'D:/archive/StereoMixPrototype'
          EDITOR: false
          ENCRYPT_INI: true
          RELEASE: '0.1.0'
          # PATCH: '0.9.0'
          # MAPS: 'Map1,Map2'